services:
  tos-analysis-service:
    image: enhesa-tos-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enhesa-tos-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - ENV=production
    restart: always